after-startup-command = ['exec-and-forget', 'exec-and-forget borders active_color=0xffe1e3e4 inactive_color=0xff494d64 width=5.0']

start-at-login = true

[workspace-to-monitor-force-assignment]
1 = 1
2 = 'secondary'

[gaps]
inner.horizontal =  10
inner.vertical =    10
outer.left =        10
outer.bottom =      10
outer.right =       10
outer.top =         10

[[on-window-detected]]
if.app-name-regex-substring = 'finder'
run = 'layout floating'

[[on-window-detected]]
if.app-name-regex-substring = 'discord'
run = 'layout floating'

[mode.main.binding]
alt-shift-cmd-slash = 'layout tiles horizontal vertical'
alt-shift-cmd-comma = 'layout accordion horizontal vertical'

shift-cmd-1 = 'workspace 1'
shift-cmd-2 = 'workspace 2'
alt-shift-cmd-1 = 'move-node-to-workspace 1'
alt-shift-cmd-2 = 'move-node-to-workspace 2'

alt-shift-cmd-f = 'fullscreen'

alt-shift-cmd-h = 'focus left'
alt-shift-cmd-j = 'focus down'
alt-shift-cmd-k = 'focus up'
alt-shift-cmd-l = 'focus right'

alt-shift-cmd-v = 'exec-and-forget open -a /Applications/Ghostty.app/'
# alt-shift-cmd-s = 'exec-and-forget open -a /Applications/Slack.app'
alt-shift-cmd-a = 'exec-and-forget open -a /Applications/Arc.app'
# alt-shift-cmd-d = 'exec-and-forget open -a /Applications/Discord.app'
alt-shift-cmd-m = 'exec-and-forget open -b com.apple.Music'
# alt-shift-cmd-t = 'exec-and-forget open -a /Applications/Linear.app/'
