- hosts: all
  vars:
    brew_cask_packages:
      - raycast
      - karabiner-elements
    brew_packages:
      - stow
      - koekeishiya/formulae/yabai
      - koekeishiya/formulae/skhd
      - kitty
      - tmux
      - neovim
      - gh
      - lazygit
      - ripgrep
      - node

    tasks: 
    - name: Installing Homebrew Cask Packages
      homebrew_cask:
        name: "{{ brew_cask_packages }}"
    - name: Installing Homebrew Packages
      homebrew:
        name: "{{ brew_packages }}"
    - name: "Stow files"
      ansible.buildin.shell: 'stow ~/.config/zsh'
      ansible.buildin.shell: 'stow ~/.config/bin'
      ansible.buildin.shell: 'stow ~/.config/git/'
      ansible.buildin.shell: 'stow -d ~/.config/fonts/ -t ~/Library/Fonts ComisShannsMono'
      ansible.buildin.shell: 'stow -d ~/.config/fonts/ -t ~/Library/Fonts 3270'
