---
- name: Install MacOS Packages
  hosts: localhost
  become: false

  pre_tasks:
  tasks: 
  - include_tasks: ansible/dev-env.yml
  - include_tasks: ansible/personal-tools.yml
  - include_tasks: ansible/work-tools.yml

